GH actions pipeline optimized

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,20 +14,20 @@ jobs:
         image: postgres:13
         ports:
           - "5432:5432"
-        options: >-
-          --health-cmd="pg_isready -U postgres" 
-          --health-interval=10s 
-          --health-timeout=5s 
-          --health-retries=3
+        # options: >-
+        #   --health-cmd="pg_isready -U postgres"
+        #   --health-interval=10s
+        #   --health-timeout=5s
+        #   --health-retries=3
       mongo:
         image: mongo:4
         ports:
           - "27017:27017"
-        options: >-
-          --health-cmd="echo 'db.runCommand({ ping: 1 })' | mongo --quiet"
-          --health-interval=10s
-          --health-timeout=5s
-          --health-retries=3
+        # options: >-
+        #   --health-cmd="echo 'db.runCommand({ ping: 1 })' | mongo --quiet"
+        #   --health-interval=10s
+        #   --health-timeout=5s
+        #   --health-retries=3
 
     steps:
       - name: Checkout code
@@ -41,33 +41,33 @@ jobs:
       - name: Install Dependencies
         run: yarn install
 
-      # - name: Run Tests
-      #   run: yarn test
+      - name: Create .env.production file
+        run: |
+          echo "NODE_ENV=production" > .env.production
+          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env.production
+          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env.production
+          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env.production
+          echo "MONGO_URI=mongodb://mongo-db:27017/${{ secrets.MONGO_DB }}" >> .env.production
 
       - name: Build Docker Image for Production
-        run: |
-          docker build -t backend:prod --build-arg NODE_ENV=production .
-
-      # - name: Run Backend in Production Mode
-      #   run: |
-      #     docker run -e NODE_ENV=production -p 8080:8080 backend:prod
+        run: docker build -t backend:prod --build-arg NODE_ENV=production .
 
       - name: Run Backend in Production Mode
         run: |
           docker run -d --name backend-prod \
             --link postgres:postgres-db \
             --link mongo:mongo-db \
-            -e NODE_ENV=production \
-            -e POSTGRES_USER=user \
-            -e POSTGRES_PASSWORD=password \
-            -e POSTGRES_DB=example \
-            -e POSTGRES_HOST=postgres-db \
-            -e MONGO_URI=mongodb://mongo-db:27017/your_database \
+            --env-file .env.production \
             -p 8080:8080 backend:prod
 
-      # - name: Run Production Tests
-      #   run: |
-      #     curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080 || exit 1
+      - name: Run Production Tests
+        run: curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:8080 || exit 1
+
+      # - name: Notify Slack
+      #   uses: rtCamp/action-slack-notify@v2
+      #   with:
+      #     webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
+      #     message: "Build and Deploy completed successfully!"
 
       - name: Clean up
         run: |
